# .goreleaser.yml
# Build customization
project_name: sub-mariadb
builds:
  - binary: pub-mssql
    ldflags: -s -w -X main.version={{.Version}} -X main.versionHash={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64